########################################################################################################################
# Customer region-specific parameters that are shared by multiple apps
########################################################################################################################
# region is the AWS region name
region: "eu-central-1"
regionNickname: "eu-central-1"

# The name of the tenant
tenantName: "turtle"

# tenantDomain is the domain suffix for customer for region
tenantDomain: "turtle.eu1.ping-preview.cloud"

# environmentPrefix is the prefix used to distinguish between worker apps for different CDEs in P14C
# and to form the Signal Science Agent name as displayed in SigSci Dashboard.
environmentPrefix: "turtle-${REGION_ENV}-eu-central-1"

# TODO: we can only substitute env vars region->base PDO-3957 to fix
regionEnv: "customer-hub"

# artifactRepoUrl is the Customer-specific artifacts URL for region
artifactRepoUrl: "s3://bootstrap-customer-hub-turtle-4-pingbinarybucket-1aznd29dpniov"

# dnsZone is the Customer-specific region DNS zone
dnsZone: "turtle.eu1.ping-preview.cloud"

# irsaPingAnnotationKeyValue is the IAM roles for service accounts
irsaPingAnnotationKeyValue: ""




########################################################################################################################
#TODO: Are these needed anymore now that we're using values files?
# If they are needed uncomment & move to the 1st section
# If they are still commented out when we get to PDO-4842, they will be deleted
########################################################################################################################
# TODO: we can only substitute env vars region->base PDO-3957 to fix
#regionEnv: customer-hub


########################################################################################################################
#TODO: Move these to app values.yaml files as apps migrate
# If they are needed by more than 1 app, move to the 1st section
########################################################################################################################
# irsaAnnotationKeyValue is the IAM roles for service accounts
irsaPaAnnotationKeyValue: ""
irsaPdAnnotationKeyValue: ""
irsaPfAnnotationKeyValue: ""

# nlbNgxPublicAnnotationKeyValue is the annotation used by ingress-nginx service in ingress-nginx-public namespace
nlbNgxPublicAnnotationKeyValue: ""

# newRelicEnvironmentName is the name of the environment as it will appear on the NewRelic console.
newRelicEnvironmentName: "turtle_${REGION_ENV}_eu-central-1_k8s-cluster"

# clusterStateRepoPath is the customer-specific region name
clusterStateRepoPath: "eu-central-1"
